using System.Text;
using FluentAssertions;
using NUnit.Framework;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using Template_net10.Application.Abstractions.Pdf;
using Template_net10.Infrastructure.Services.Pdf;

namespace Template_net10.UnitTests.Infrastructure.Documents;

[TestFixture]
public sealed class PdfGeneratorTests
{
    [Test]
    public void Render_produces_a_valid_pdf()
    {
        IPdfGenerator generator = new QuestPdfGenerator();

        var report = new PdfReport
        {
            Title = "Users Report",
            Subtitle = "Generated by tests",
            Columns = ["Name", "Email"],
            Rows =
            [
                ["Alice", "alice@example.com"],
                ["Bob", "bob@example.com"],
            ],
            FooterNote = "Confidential",
        };

        var bytes = generator.Render(report);

        bytes.Should().NotBeEmpty();
        Encoding.ASCII.GetString(bytes, 0, 5).Should().Be("%PDF-");
    }

    [Test]
    public void Render_applies_custom_design_options()
    {
        IPdfGenerator generator = new QuestPdfGenerator();

        var report = new PdfReport
        {
            Title = "Branded Report",
            Columns = ["A", "B", "C"],
            Rows = [["1", "2", "3"], ["4", "5", "6"]],
            Design = new PdfDesign
            {
                PageSize = PdfPageSize.A5,
                Landscape = true,
                AccentColorHex = "#2563EB",
                ColumnWidths = [2f, 1f, 1f],
                ZebraRows = true,
                Margin = 20f,
                BaseFontSize = 9f,
            },
        };

        var bytes = generator.Render(report);

        bytes.Should().NotBeEmpty();
        Encoding.ASCII.GetString(bytes, 0, 5).Should().Be("%PDF-");
    }

    [Test]
    public void Render_throws_when_no_columns()
    {
        IPdfGenerator generator = new QuestPdfGenerator();

        var act = () => generator.Render(new PdfReport { Title = "Empty" });

        act.Should().Throw<ArgumentException>();
    }

    private sealed class CustomInvoiceDocument : PdfDocumentBase
    {
        public override void Compose(IDocumentContainer container)
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.Content().Text("Fully custom layout").FontSize(24).Bold();
            });
        }
    }

    [Test]
    public void Renderer_renders_a_custom_document()
    {
        IPdfRenderer renderer = new QuestPdfGenerator();

        var bytes = renderer.Render(new CustomInvoiceDocument());

        bytes.Should().NotBeEmpty();
        Encoding.ASCII.GetString(bytes, 0, 5).Should().Be("%PDF-");
    }

    [Test]
    public void Renderer_renders_an_inline_compose_delegate()
    {
        IPdfRenderer renderer = new QuestPdfGenerator();

        var bytes = renderer.Render(container => container.Page(page =>
        {
            page.Size(PageSizes.A4);
            page.Margin(30);
            page.Content().Text("Inline custom design").FontSize(16);
        }));

        bytes.Should().NotBeEmpty();
        Encoding.ASCII.GetString(bytes, 0, 5).Should().Be("%PDF-");
    }
}
